twig:
    default_path: '%kernel.project_dir%/templates'
<<<<<<< HEAD
    form_themes: ['bootstrap_4_layout.html.twig']

=======
    form_themes: ['bootstrap_5_layout.html.twig']
    
>>>>>>> 5962a778d426c1945a80ef5358f062bdd60a3e50
when@test:
    twig:
        strict_variables: true
